using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Entity_ : MonoBehaviour {
  
  public SO_Entity entityData;
  public int facingDirection { get; private set; }
  public Rigidbody2D rb { get; private set; }
  public Animator animator { get; private set; }
  public GameObject aliveGO { get; private set; }
  public AnimationToStateMachine atsm { get; private set; }

    private EnemyState currentState;

    public bool flipAfterIdle;

    [SerializeField]
  private Transform wallCheck;
  [SerializeField]
  private Transform ledgeCheck;
  [SerializeField]
  private Transform playerCheck;

  private Vector2 velocityWorkspace;

  public virtual void Start() {
    facingDirection = 1;
    aliveGO = gameObject;
    rb = aliveGO.GetComponent<Rigidbody2D>();
    animator = aliveGO.GetComponent<Animator>();
    atsm = aliveGO.GetComponent<AnimationToStateMachine>();
        flipAfterIdle = false;
  }

  public virtual void Update() {

  }

    public virtual void FixedUpdate() 
    {
        if (currentState) 
        { 
            currentState.OnFixedUpdate();
        }
    }

    public void ChangeCurrentState(EnemyState newState)
    {
        currentState = newState;
    }

  public virtual void SetVelocity(float velocity) {
    velocityWorkspace.Set(facingDirection * velocity, rb.velocity.y);
    rb.velocity = velocityWorkspace;
  }

    public void SetFlipAfterIdle(bool flip)
    {
        flipAfterIdle = flip;
    }

    public virtual bool CheckWall() {
    return Physics2D.Raycast(wallCheck.position, aliveGO.transform.right, entityData.wallCheckDistance, entityData.whatIsGround);
  }

  public virtual bool CheckLedge() {
    return Physics2D.Raycast(ledgeCheck.position, Vector2.down, entityData.ledgeCheckDistance, entityData.whatIsGround);
  }

  public virtual bool CheckPlayerInMinAggroRange() {
    return Physics2D.Raycast(playerCheck.position, aliveGO.transform.right, entityData.minAggroDistance, entityData.whatIsPlayer);
  }

  public virtual bool CheckPlayerInMaxAggroRange() {
    return Physics2D.Raycast(playerCheck.position, aliveGO.transform.right, entityData.maxAggroDistance, entityData.whatIsPlayer);
  }

  public virtual bool CheckPlayerInCloseRangeAction() {
    return Physics2D.Raycast(playerCheck.position, aliveGO.transform.right, entityData.closeRangeActionDistance, entityData.whatIsPlayer);
  }

  public virtual void Flip() {
    facingDirection *= -1;
    aliveGO.transform.Rotate(0f, 180f, 0f);
  }

  public virtual void OnDrawGizmos() {
    Debug.DrawLine(wallCheck.position, wallCheck.position + (Vector3)(Vector2.right * facingDirection * entityData.wallCheckDistance), Color.blue);
    Debug.DrawLine(ledgeCheck.position, ledgeCheck.position + (Vector3)(Vector2.down * entityData.ledgeCheckDistance), Color.blue);
    Gizmos.DrawWireSphere(playerCheck.position + (Vector3)(Vector2.right * entityData.closeRangeActionDistance), 0.2f);
      Gizmos.DrawWireSphere(playerCheck.position + (Vector3)(Vector2.right * entityData.minAggroDistance), 0.2f);
      Gizmos.DrawWireSphere(playerCheck.position + (Vector3)(Vector2.right * entityData.maxAggroDistance), 0.2f);
  }

}
